"""initial migration

Revision ID: 1
Revises:
Create Date: 2021-01-28 21:45:48.821421

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('key_and_nullable',
                  sa.Column('id', sa.Integer(), nullable=False),
                  sa.PrimaryKeyConstraint('id'))
  op.create_table('key_only', sa.Column('id', sa.Integer(), nullable=False),
                  sa.PrimaryKeyConstraint('id'))
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('key_only')
  op.drop_table('key_and_nullable')
  # ### end Alembic commands ###
