"""add comments

Revision ID: 2
Revises: 1
Create Date: 2021-01-28 21:53:46.789727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_and_nullable', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='auto-incrementing key',
               autoincrement=True)
    op.alter_column('key_only', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='auto-incrementing key',
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('key_only', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='auto-incrementing key',
               autoincrement=True)
    op.alter_column('key_and_nullable', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='auto-incrementing key',
               autoincrement=True)
    # ### end Alembic commands ###
